.idea/.name
=> Fixed the project name to haber-webdev

.idea/deployment.xml, .idea/misc.xml, .idea/vcs.xml, .idea/webServers.xml, web/src/stylesheets/default/components/_activities.scss, web/src/stylesheets/default/pages/page--sales-rep-entry.scss
Updated styles for the Topic area of the Weekly Team Meeting activity
Updated styles for the Manager Profile section for activity management
=> HAB-1220 | HAB-1221

web/src/stylesheets/default/components/_dashboard.scss
Flipped box order, updated styles to match.
=> HAB-1252 - Update Dashboard Boxes

web/src/stylesheets/default/templates/template--base.scss
Added styles for the front end user cheer component
=> HAB-1270 - Cheer Editor UI

web/src/javascript/default/pages/page--period-selector.js, web/src/javascript/default/templates/main.js
Fix select2 initialization for main templates.
=> HAB-1282 - Select2 Initialization

web/src/stylesheets/default/components/_prop-ui.scss, web/src/stylesheets/default/pages/page--client-mgt.scss, web/src/stylesheets/default/templates/template--base.scss
HAB-1273 - Cheer Config Editor 
Includes some front end tweaks
=> HAB-1273 - Cheer Config Editor 

web/src/javascript/default/templates/main.js, web/src/stylesheets/default/pages/page--coaching-library.scss
Updated initialization to use style for the width rather than calculating the width and setting an inline style.
=> Hab-1295 - Updated select2 Init

web/src/stylesheets/default/pages/page--login.scss
Fixed styles on the reset pawsword page.  Adjusted for now-hidden content.
=> Hab-1254 - Reset Password Style Update

web/src/javascript/default/templates/main.js, web/src/stylesheets/default/components/_search-ui.scss
Added an overflow for the result table as the search in this case was requested to have a large number of columns.
=> HAB-834 - Activity Instance Management

web/src/stylesheets/default/pages/page--my-reports.scss
Added padding to download button
=> HAB-1288 - Activities Done On Time Report

web/src/stylesheets/default/components/_activities.scss
Implemented attachments - include text transform on attachment links
=> HAB-1225 - Activity Attachments

web/src/stylesheets/default/components/_starter-menu.scss, web/src/stylesheets/default/pages/page--cheer-editor.scss
Fixed text align, removed some extra spacing, and made minor updates.
=> HAB-1289 - Cheer Editor

web/src/javascript/default/templates/template--app.js, web/src/stylesheets/default/components/_dashboard.scss
Adjusted min width of dashboard search.
Changed width of select2 initialization to use the stylesheet.
=> HAB-1299 - Header Fixes

web/src/stylesheets/default/components/_search-ui.scss
Added padding to date range input field
=> HAB-1307 - Activity mgt

web/src/stylesheets/default/components/_search-ui.scss
Changed overflow rule to auto because why you not want auto?
=> HAB-1309 - Search Result Table

web/src/stylesheets/default/components/_activities.scss, web/src/stylesheets/default/components/_general-app.scss, web/src/stylesheets/default/components/_starter-menu.scss, web/src/stylesheets/default/config/_base-vars.scss, web/src/stylesheets/default/pages/page--cheer-editor.scss
Updated heading styles, fixes.
Changed icon for activity search
=> HAB-1310 - Heading Style Updates

web/src/stylesheets/default/components/_general-app.scss
Updated activity search icon under profile picture
=> HAB-1310 - Updated Icon

web/src/stylesheets/default/pages/page--my-reports.scss
Added padding between report elements.
=> HAB-1317 - Report Padding

web/src/javascript/default/pages/page--period-selector.js
Updated default period selection on demo dashboard.
=> HAB-1173 - Default Demo Dashboard to Fiscal Year to date

web/src/stylesheets/default/components/_dashboard.scss, web/src/stylesheets/default/components/_general-app.scss, web/src/stylesheets/default/components/_starter-menu.scss, web/src/stylesheets/default/pages/page--coaching-library.scss
=> Feedback updates round 2

web/src/stylesheets/default/components/_weekly-team-meeting.scss
=> Feedback updates - not actually a button
